development:
  clients:
    default:
      database: blog_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
  options:
    raise_not_found_error: false


production:
  clients:
    default:
      database: visual_sphere_production
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
  options:
    raise_not_found_error: false